//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSolicitudes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoxEstado
    {
        public int idArchivoxEstado { get; set; }
        public Nullable<int> FK_idArchivo { get; set; }
        public Nullable<int> FK_idEstado { get; set; }
    
        public virtual Archivos Archivos { get; set; }
        public virtual EstadoSolicitud EstadoSolicitud { get; set; }
    }
}
