//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSolicitudes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Fotos = new HashSet<Fotos>();
            this.ZonaxSolicitud = new HashSet<ZonaxSolicitud>();
            this.RangoxSolicitud = new HashSet<RangoxSolicitud>();
            this.FotosSeisMeses = new HashSet<FotosSeisMeses>();
            this.FotosTresMeses = new HashSet<FotosTresMeses>();
            this.FotosUnMes = new HashSet<FotosUnMes>();
        }
    
        public int idSolicitud { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string RespDerm { get; set; }
        public string RespPelo { get; set; }
        public string ObserMed { get; set; }
        public Nullable<int> ValorTotal { get; set; }
        public Nullable<int> FK_idCliente { get; set; }
        public Nullable<int> Fk_idEstado { get; set; }
        public Nullable<int> FK_idCiudad { get; set; }
        public Nullable<int> FK_SLA { get; set; }
        public Nullable<int> FK_Tecnica { get; set; }
        public Nullable<int> FK_Rango { get; set; }
        public Nullable<int> FK_idUsuario { get; set; }
        public string RespZona { get; set; }
        public Nullable<int> SolicitudCompleta { get; set; }
        public string idPipedrive { get; set; }
        public Nullable<System.DateTime> FechaEvaluacionPresencial { get; set; }
        public Nullable<System.DateTime> FechaCirugia { get; set; }
        public Nullable<System.DateTime> FechaLlamada { get; set; }
        public Nullable<System.DateTime> FechaEvaluaciónOnceMeses { get; set; }
        public string ObserCuidado { get; set; }
        public Nullable<System.DateTime> FechaCirugiaGarantia { get; set; }
        public Nullable<System.DateTime> UltimoCambio { get; set; }
        public Nullable<System.DateTime> EvaluacionPresencial { get; set; }
        public Nullable<bool> Foto1Mes { get; set; }
        public Nullable<bool> Foto3Mes { get; set; }
        public Nullable<bool> Foto6Mes { get; set; }
        public Nullable<bool> DiaCirugiaEnviado { get; set; }
        public Nullable<System.DateTime> FechaCirugiaPaciente { get; set; }
        public Nullable<bool> Leido { get; set; }
        public string Enviado { get; set; }
        public string Guardado { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoSolicitud EstadoSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotos> Fotos { get; set; }
        public virtual RangoFoliculos RangoFoliculos { get; set; }
        public virtual SLA SLA { get; set; }
        public virtual Tecnica Tecnica { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZonaxSolicitud> ZonaxSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RangoxSolicitud> RangoxSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotosSeisMeses> FotosSeisMeses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotosTresMeses> FotosTresMeses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotosUnMes> FotosUnMes { get; set; }
    }
}
