//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSolicitudes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tecnica()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int idTecnica { get; set; }
        public string nombreTecnica { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ValorTecnica { get; set; }
        public string cod_Tecnica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
